news_sites:
  eluniversal:
    url:  https://www.eluniversal.com.mx/
    queries:
      homepage_aricle_links = '.field-content a'
  elpais:
    url:  https://elpais.com/elpais/portada_america.html


